#!/usr/bin/env python3
"""gen_swift.py — generate the canonical shared Swift module from the contracts.

Sibling of gen_shared.py (Python) + gen_ts.py (JS). Single source of truth:
`contracts/*.schema.json` (the wire enums) + `constants/cluster.yaml` (the migration
lifecycle). Emits Swift enums so the desktop client stops hand-maintaining a parallel
`MigrationState` enum + event/job string literals (CRIE 002 #8/#4).

Output is **client-safe**: enums + DTOs only — NO broker/NATS constants (the desktop
client is public and never touches the broker).

  - `libs/swift/LudoShared/Generated.swift`

The desktop repo VENDORS this file into its SwiftPM target sources (byte-identical copy);
drift is guarded by check_shared_drift.py. Run: `python scripts/gen_swift.py` (needs PyYAML).
Re-run after any contract/cluster change.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CONTRACTS = REPO / "contracts"
CLUSTER = REPO / "constants" / "cluster.yaml"
OUT = REPO / "libs" / "swift" / "LudoShared" / "Generated.swift"


def _camel(value: str) -> str:
    """`gap-fix`/`dry_run` -> `gapFix`/`dryRun` (lowerCamelCase Swift case names)."""
    parts = value.replace("-", "_").split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _string_enum(name: str, values: list[str], doc: str) -> str:
    """A `String`-raw enum; raw value is the wire string, case name is camelCased."""
    cases = "\n".join(f'    case {_camel(v)} = "{v}"' for v in values)
    return (
        f"/// {doc}\n"
        f"public enum {name}: String, Codable, CaseIterable, Sendable {{\n{cases}\n}}\n"
    )


def main() -> int:
    cluster = yaml.safe_load(CLUSTER.read_text(encoding="utf-8"))
    states = list(cluster["migration"]["states"])

    job = json.loads((CONTRACTS / "job-message.schema.json").read_text(encoding="utf-8"))
    event = json.loads((CONTRACTS / "session-event.schema.json").read_text(encoding="utf-8"))
    job_types = job["properties"]["type"]["enum"]
    event_types = event["properties"]["type"]["enum"]

    state_cases = "\n".join(
        f"    case {_camel(s.lower())}{'' if i else ' = 0'}" for i, s in enumerate(states)
    )
    state_labels = "\n".join(f'        case .{_camel(s.lower())}: return "{s}"' for s in states)
    states_arr = ", ".join(f'"{s}"' for s in states)

    swift = "".join([
        "// AUTO-GENERATED by scripts/gen_swift.py — do not edit by hand.\n",
        "// Source of truth: ludo-init/contracts/*.schema.json + constants/cluster.yaml.\n",
        "// Regenerate with `python scripts/gen_swift.py` after any contract/cluster change.\n",
        "// Client-safe: enums only (no broker/NATS internals).\n\n",
        "import Foundation\n\n",
        "// MARK: - Migration lifecycle (constants/cluster.yaml :: migration.states)\n\n",
        f"public let MIGRATION_STATES: [String] = [{states_arr}]\n\n",
        "/// Control-plane Migration.state_index (0-indexed) -> human label.\n",
        "public enum MigrationState: Int, CaseIterable, Sendable {\n",
        f"{state_cases}\n",
        "    public var label: String {\n",
        "        switch self {\n",
        f"{state_labels}\n",
        "        }\n",
        "    }\n",
        "}\n\n",
        "// MARK: - Contract B enums (contracts/*.schema.json)\n\n",
        _string_enum("JobType", job_types, "Dispatch key (gateway -> agent). Mirror of the job-message schema."),
        "\n",
        _string_enum("EventType", event_types, "Session-event type (agent -> gateway). Mirror of the session-event schema."),
    ])

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(swift, encoding="utf-8")
    print(f"[ok] wrote {OUT.relative_to(REPO)} "
          f"({len(job_types)} job types, {len(event_types)} event types, "
          f"{len(states)} migration states)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
