#!/usr/bin/env python3
"""gen_ts.py — generate the canonical shared JS/TS module from the contracts.

Sibling of gen_shared.py (Python). Single source of truth: `contracts/*.schema.json`
(the wire enums) + `constants/cluster.yaml` (the migration lifecycle). Emits a
dependency-free ESM module so the JS frontends (and any future TS client) stop
hand-maintaining parallel copies of the migration states / event / job enums
(CRIE 002 #8/#101).

Output is **client-safe**: enums + lifecycle labels only — NO broker/NATS constants
(those stay internal to the private Python repos; public clients never touch the broker).

  - `libs/ts/ludo_shared/generated.js`   — runtime values (frozen arrays/objects)
  - `libs/ts/ludo_shared/generated.d.ts` — type declarations (string-literal unions)

Consumers VENDOR the `ludo_shared/` dir (byte-identical copy) like they vendor
`contracts/`; drift is guarded by check_shared_drift.py. Run: `python scripts/gen_ts.py`
(needs PyYAML). Re-run after any contract/cluster change.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CONTRACTS = REPO / "contracts"
CLUSTER = REPO / "constants" / "cluster.yaml"
OUT_DIR = REPO / "libs" / "ts" / "ludo_shared"

_HEADER = (
    "// AUTO-GENERATED by scripts/gen_ts.py — do not edit by hand.\n"
    "// Source of truth: agentix/contracts/*.schema.json + constants/cluster.yaml.\n"
    "// Regenerate with `python scripts/gen_ts.py` after any contract/cluster change.\n"
    "// Client-safe: enums + lifecycle labels only (no broker/NATS internals).\n"
)


def _js_enum(name: str, values: list[str]) -> str:
    """Frozen object whose keys are the UPPER_CASED values (mirrors the Python StrEnum)."""
    body = "\n".join(f'  {v.upper()}: "{v}",' for v in values)
    return f"export const {name} = Object.freeze({{\n{body}\n}})\n"


def _ts_union(name: str, values: list[str]) -> str:
    members = " | ".join(f'"{v}"' for v in values)
    return f"export type {name} = {members}\n"


def main() -> int:
    cluster = yaml.safe_load(CLUSTER.read_text(encoding="utf-8"))
    states = list(cluster["migration"]["states"])

    job = json.loads((CONTRACTS / "job-message.schema.json").read_text(encoding="utf-8"))
    event = json.loads((CONTRACTS / "session-event.schema.json").read_text(encoding="utf-8"))
    job_types = job["properties"]["type"]["enum"]
    event_types = event["properties"]["type"]["enum"]

    states_arr = ", ".join(f'"{s}"' for s in states)

    js = "".join([
        _HEADER,
        "\n",
        "// ── Migration lifecycle — constants/cluster.yaml :: migration.states ──\n",
        f"export const MIGRATION_STATES = Object.freeze([{states_arr}])\n\n",
        "// Human label for a state_index; falls back to `State N` out of range.\n",
        "export function migrationStateLabel(index) {\n"
        "  return MIGRATION_STATES[index] ?? `State ${index}`\n"
        "}\n\n",
        "// ── Contract B enums — contracts/*.schema.json ──\n",
        _js_enum("JobType", job_types),
        "\n",
        _js_enum("EventType", event_types),
    ])

    states_tuple = ", ".join(f'"{s}"' for s in states)
    dts = "".join([
        _HEADER,
        "\n",
        f"export declare const MIGRATION_STATES: readonly [{states_tuple}]\n",
        "export declare function migrationStateLabel(index: number): string\n\n",
        _ts_union("JobType", job_types),
        "export declare const JobType: Readonly<Record<string, JobType>>\n\n",
        _ts_union("EventType", event_types),
        "export declare const EventType: Readonly<Record<string, EventType>>\n",
    ])

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "generated.js").write_text(js, encoding="utf-8")
    (OUT_DIR / "generated.d.ts").write_text(dts, encoding="utf-8")
    print(f"[ok] wrote {(OUT_DIR / 'generated.js').relative_to(REPO)} + .d.ts "
          f"({len(job_types)} job types, {len(event_types)} event types, "
          f"{len(states)} migration states)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
