"""Driver stub code generator."""

from __future__ import annotations

_CHAT_STUB = '''\
"""
{name} — chat driver stub generated by `agentix scaffold driver {name}`.

Implement `complete()` and optionally `stream()`, then register:

    # in your app's startup
    from agentix.drivers.factory import register_driver_factory
    from {module_name} import {class_name}

    register_driver_factory("{key}", lambda spec, **kw: {class_name}(spec=spec, **kw))

See docs/drivers.md for the full driver contract.
"""

from __future__ import annotations

from agentix.drivers.base import ChatDriver, DriverDescriptor
from agentix.drivers.types import ChatRequest, ChatResponse, StreamChunk


class {class_name}(ChatDriver):
    descriptor = DriverDescriptor(
        name="{key}",
        type="model",
        modality="chat",
        source="api",
    )

    async def complete(self, request: ChatRequest) -> ChatResponse:
        raise NotImplementedError("{class_name}.complete() not implemented")

    async def stream(self, request: ChatRequest):  # type: ignore[override]
        raise NotImplementedError("{class_name}.stream() not implemented")
        yield StreamChunk(delta="")  # pragma: no cover


__all__ = ["{class_name}"]
'''

_EMBEDDING_STUB = '''\
"""
{name} — embedding driver stub generated by `agentix scaffold driver {name}`.

Implement `embed()`, then register:

    from agentix.drivers.factory import register_driver_factory
    from {module_name} import {class_name}

    register_driver_factory("{key}", lambda spec, **kw: {class_name}(spec=spec, **kw))

See docs/drivers.md for the full driver contract.
"""

from __future__ import annotations

from agentix.drivers.base import DriverDescriptor, EmbeddingDriver
from agentix.drivers.types import EmbeddingRequest, EmbeddingResponse


class {class_name}(EmbeddingDriver):
    descriptor = DriverDescriptor(
        name="{key}",
        type="model",
        modality="embedding",
        source="api",
    )

    async def embed(self, request: EmbeddingRequest) -> EmbeddingResponse:
        raise NotImplementedError("{class_name}.embed() not implemented")


__all__ = ["{class_name}"]
'''

_STT_STUB = '''\
"""
{name} — speech-to-text driver stub generated by `agentix scaffold driver {name}`.

Implement `transcribe()`, then register:

    from agentix.drivers.factory import register_driver_factory
    from {module_name} import {class_name}

    register_driver_factory("{key}", lambda spec, **kw: {class_name}(spec=spec, **kw))

See docs/drivers.md for the full driver contract.
"""

from __future__ import annotations

from agentix.drivers.base import DriverDescriptor, SttDriver
from agentix.drivers.types import SttRequest, SttResponse


class {class_name}(SttDriver):
    descriptor = DriverDescriptor(
        name="{key}",
        type="model",
        modality="stt",
        source="api",
    )

    async def transcribe(self, request: SttRequest) -> SttResponse:
        raise NotImplementedError("{class_name}.transcribe() not implemented")


__all__ = ["{class_name}"]
'''

_STUBS: dict[str, str] = {
    "chat": _CHAT_STUB,
    "embedding": _EMBEDDING_STUB,
    "stt": _STT_STUB,
}


def _to_class_name(name: str) -> str:
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_")) + "Driver"


def _to_key(name: str) -> str:
    return name.lower().replace("_", "-")


def _to_module(name: str) -> str:
    return name.lower().replace("-", "_")


def render_driver(name: str, modality: str) -> tuple[str, str]:
    """Return (filename, content) for a driver stub."""
    if modality not in _STUBS:
        raise ValueError(f"unknown modality {modality!r}; choose from: {list(_STUBS)}")
    template = _STUBS[modality]
    class_name = _to_class_name(name)
    key = _to_key(name)
    module_name = _to_module(name)
    content = template.format(name=name, class_name=class_name, key=key, module_name=module_name)
    filename = f"{module_name}.py"
    return filename, content
